### ISSUE TITLE
Failing to operate on certain M2TS files.

### ISSUE THREAD

**Issue by capriciouswhim** [l33tmeatwad/AMVtool#2]
Input #0, mpegts, from 'B:/[redacted].m2ts':
  Duration: 00:22:52.10, start: 11.650667, bitrate: 32283 kb/s
  Program 1 
    Stream #0:0[0x1011]: Video: h264 (High) (HDMV / 0x564D4448), yuv420p(tv, bt709, progressive), 1920x1080 [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 90k tbn, 47.95 tbc
    Stream #0:1[0x1100]: Audio: truehd (AC-3 / 0x332D4341), 48000 Hz, 5.1(side), s32 (24 bit)
    Stream #0:2[0x1100]: Audio: ac3 (AC-3 / 0x332D4341), 48000 Hz, 5.1(side), fltp, 448 kb/s
    Stream #0:3[0x1101]: Audio: truehd (AC-3 / 0x332D4341), 48000 Hz, stereo, s32 (24 bit)
    Stream #0:4[0x1101]: Audio: ac3 (AC-3 / 0x332D4341), 48000 Hz, stereo, fltp, 192 kb/s
    Stream #0:5[0x1102]: Audio: truehd (AC-3 / 0x332D4341), 48000 Hz, stereo, s32 (24 bit)
    Stream #0:6[0x1102]: Audio: ac3 (AC-3 / 0x332D4341), 48000 Hz, stereo, fltp, 192 kb/s
    Stream #0:7[0x1200]: Subtitle: hdmv_pgs_subtitle ([144][0][0][0] / 0x0090), 1920x1080
    Stream #0:8[0x1201]: Subtitle: hdmv_pgs_subtitle ([144][0][0][0] / 0x0090)
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
  Stream #0:2 -> #0:2 (copy)
  Stream #0:3 -> #0:3 (copy)
  Stream #0:4 -> #0:4 (ac3 (native) -> aac (native))
  Stream #0:5 -> #0:5 (truehd (native) -> aac (native))
  Stream #0:6 -> #0:6 (ac3 (native) -> aac (native))

[mp4 @ 00000165e1b18200] truehd in MP4 support is experimental, add '-strict -2' if you want to use it.
Could not write header for output file #0 (incorrect codec parameters ?): Experimental feature
Error initializing output stream 0:6 --

**Comment by capriciouswhim** [comment]
I don't need the truehd audio.  AC3 versions are fine.  Can we tell it to ignore truehd streams, for now?

**Comment by l33tmeatwad** [comment]
I will see about fixing that, for now you can work around it by recontainering to MKV with MKVtoolNix  without the TrueHD streams and then recontainer to MP4 with AMVtool.

**Comment by capriciouswhim** [comment]
Thanks for checking!   
  
  
  
  
  
    
  

  
  
>

**Comment by l33tmeatwad** [comment]
Sorry for the long delay on this, now from what I can tell at the time TrueHD in MP4 was experimental, but according to the changelog for FFMPEG it should be supported as of version 4.3 and not need that additional option.  I don't have a sample to work with, so if you could please try getting an updated ffmpeg executable from ffmpeg.org and let me know if that works.

**Comment by l33tmeatwad** [comment]
Added a checkbox in the new beta to allow for experimental features.
