### ISSUE TITLE
Can this be used with NVenc (hardware encoder)?

### ISSUE THREAD

**Issue by tyeeman** [l33tmeatwad/AMVtool#3]
I have an Nvidia card and would like to use this with it. Currently using Rigaya's NVencc in a batch file. Your GUI would be nice.

**Comment by l33tmeatwad** [comment]
This project isn't intended to be an extensive GUI for everything FFmpeg supports, mainly just the few features used by editors in a simplified interface with an emphasis on quality.  Additionally I don't want to focus on features that aren't universal to avoid confusion, so this is not something planned for now.
