### ISSUE TITLE
Audio Glitch

### ISSUE THREAD

**Issue by itsAvient** [l33tmeatwad/AMVtool#4]
I don't know if this is an issue stemming from AMVtool or the codecs I'm using (Input File). I generally render with either Lagarith or UT Video Codec 420 709 (the issue happens on both) but when I run them through AMVtool.
Quantizer 16, Speed Very Slow, No Tune Preset.
The output file's audio at the very end has a static glitch noise, the same noise you hear when you switch television channels on the old CRT monitors. It happens to all the files that I run through AMVtool, not sure what the issue is.

**Comment by l33tmeatwad** [comment]
I would actually need to know the details of the audio to be able to help with this, you only provided details about the video stream.  Can you check one of the files with MediaInfo and share the details?

**Comment by itsAvient** [comment]
yup! Here you are!
[MEDIAINFO.txt](https://github.com/l33tmeatwad/AMVtool/files/7268591/MEDIAINFO.txt)

**Comment by l33tmeatwad** [comment]
I apologize, I should have been more specific, I need the information for the input video, not the final encode.

**Comment by itsAvient** [comment]
Ah! Sorry about that
Here's a different file's MediaInfo for the inpu
[AUDIO MEDIAINFO.TXT](https://github.com/l33tmeatwad/AMVtool/files/7268631/AUDIO.MEDIAINFO.TXT)
t.

**Comment by l33tmeatwad** [comment]
Is this glitch happening in multiple different media players or one specifically?

**Comment by itsAvient** [comment]
it happens on VLC as well as discord embed, havent tried in others but because i'm sending the files around others confirmed to hear it too

**Comment by l33tmeatwad** [comment]
What version of AMVtool are you using?

**Comment by itsAvient** [comment]
1.1 as of yesterday, before that 1.0.1.5 , same issue on both though.

**Comment by l33tmeatwad** [comment]
And you tested playback of the source file and it does not have that glitch at the end?

**Comment by itsAvient** [comment]
yeah it doesn't have it, just double checked

**Comment by itsAvient** [comment]
i'll do another render test later tonight, maybe it's inconsistent?

**Comment by l33tmeatwad** [comment]
I'll need to get some kind of sample file to work with, I'm not really sure what would be causing FFmpeg to do this specifically for your files.

**Comment by l33tmeatwad** [comment]
Would you mind providing a small sample you verified had this issue when encoded? I'd like to fix the issue, but I only can if I can replicate it.

**Comment by itsAvient** [comment]
sorry! I have a sample (after running it thru amvtool) but I'll need to re-render one as well before running it thru, I am out for most of the day, if you want I can send you a sample that has the glitch but the other file will have to wait.

**Comment by l33tmeatwad** [comment]
Sounds good, just wanted to stress I do want to address the issue. At your convenience just package together the unit and

**Comment by l33tmeatwad** [comment]
Sorry, accidently tapped close instead of comment.

**Comment by l33tmeatwad** [comment]
I'm seeing some information about FFmpeg 4.3+ having issues with some AVI files with PCM audio. Few things to try, make sure you're using the latest build if AMVtool.  First is to try encoding through an AviSynth script. If you have VirtualDub you could also try processing the audio to pcm again though that and just copy the video then encode it again.  Last, I assume you're using premiere based on Adobe being listed in the MediaInfo, if so try setting the audio to output ADPCM if that is selectable for AVI and try that.

**Comment by l33tmeatwad** [comment]
Since the FFmpeg version has been updated and I have been unable to replicate this issue I'm going to close this. If you have the same issue with the latest release just open a new issue and we can look into it again.
