### ISSUE TITLE
AvisynthWrapper.dll文件找不到哇

### ISSUE THREAD

**Issue by DidaDidaDidaD** [l33tmeatwad/AMVtool#6]
AvisynthWrapper.dll文件找不到哇

**Comment by DidaDidaDidaD** [comment]
下载了个放到目录下也不行呢，大神怎么搞

**Comment by l33tmeatwad** [comment]
I'm not sure if you are compiling it yourself or downloading a regular, but if you are compiling it the source for that file is included on the releases page. If you're downloading the release that file is included. Make sure you are extracting all files and not just the exe. Additionally, everything is compiled Microsoft Visual C++ 2015-2019, so make sure the redistributable package is installed, the link is on the releases page.
