### ISSUE TITLE
GUI for QTGMC? (feature request / suggestion)

### ISSUE THREAD

**Issue by daniel-toman** [l33tmeatwad/AMVtool#9]
I love the simplicity of this tool! The UI design is so much better than most other open source video tools I've seen.

Would you consider adding a simple UI option for using the QTGMC deinterlacer via Vapoursynth? 

Could be presented as simply as:
- [x] QTGMC Deinterlace
Preset: ( dropdown menu of Fast, Medium, Slow, etc. )

Any user who wanted something more advanced would probably be capable of using your existing Vaporsynth script support.

Many people rave about QTGMC but there is a high technical barrier to using it. There are very few GUI tools that make it available to the average video editor.

StaxRip is probably the simplest GUI tool with QTGMC, but it's only for Windows. Especially on Mac there is really no simple GUI to QTGMC available. Hybrid used to support Mac but dropped it, and that UI was never simple.

Happy to discuss further if you're interested! Thanks for considering and thanks for this great tool, I'm definitely going to add it to my regular workflow.

**Comment by l33tmeatwad** [comment]
That is really out of scope for this project. AMVtool is just meant to be a simple front end for FFmpeg intended for basic batch processes.

**Comment by daniel-toman** [comment]
Too bad, I was hoping that since AMVtool offers a deinterlace option, and supports running VapourSynth scripts, that it could be possible to offer a VapourSynth-based deinterlace option in the AMVtool GUI as well. But it sounds like that's probably more complicated to implement than I realize.

Thank you for providing AMVtool and the AMVpack with VapourSynth + Editor installers for Mac, this is extremely useful and appreciated! I do have a desire for doing batches of SD video deinterlacing with QTGMC as opposed to the ffmpeg deinterlacers, as QTGMC gives such good results with certain types of content. I will just have to figure out that workflow the hard way, but I am grateful to have these tools to use.

Cheers,
Daniel
